replicaCount: 1
image:
  repository: headscale/headscale
  pullPolicy: IfNotPresent
  tag: "latest"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  server:
    port: 8080
  metrics:
    port: 9090
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount: {}
configuration:
  server_url: http://0.0.0.0:8080
  metrics_listen_addr: 0.0.0.0:9090
  private_key_path: /etc/headscale/private.key
  noise:
    private_key_path: /etc/headscale/noise_private.key
  db_type: sqlite3
  db_path: /etc/headscale/db.sqlite
  configuration:
