---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "headscale.fullname" . }}-data
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
