---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "headscale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configuration: {{ toRawJson .Values.configuration | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "headscale.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "headscale.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["headscale"]
          args: ["serve"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "headscale.fullname" . }}-config
              mountPath: /etc/headscale/config.yaml
              subPath: config.yaml
            {{- if .Values.acl }}
            - name: {{ include "headscale.fullname" . }}-acl
              mountPath: {{ .Values.configuration.acl_policy_path }}
              subPath: {{ base .Values.configuration.acl_policy_path }} 
            {{- end }}
            - name: emptydir-volume
              mountPath: /etc/headscale 
            - name: {{ include "headscale.fullname" . }}-data
              mountPath: /var/lib/headscale
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "headscale.fullname" . }}-config
          configMap:
            name: {{ include "headscale.fullname" . }}-config
        {{- if .Values.acl }}
        - name: {{ include "headscale.fullname" . }}-acl
          configMap:
            name: {{ include "headscale.fullname" . }}-acl
        {{- end }}
        - name: emptydir-volume
          emptyDir: {}
        - name: {{ include "headscale.fullname" . }}-data 
          persistentVolumeClaim:
            claimName: {{ include "headscale.fullname" . }}-data 

