replicaCount: 1

image:
  repository: headscale/headscale
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  server:
    port: 8080
  metrics:
    port: 9090

# Example configurations:
# https://github.com/juanfont/headscale/blob/main/config-example.yaml
configuration:
  server_url: http://0.0.0.0:8080
  listen_addr: 0.0.0.0:8080
  metrics_listen_addr: 0.0.0.0:9090
  grpc_listen_addr: 0.0.0.0:50443
  grpc_allow_insecure: false
  private_key_path: /var/lib/headscale/private.key
  noise:
    private_key_path: /var/lib/headscale/noise_private.key
  ip_prefixes:
    - fd7a:115c:a1e0::/48
    - 100.64.0.0/10
  derp:
    server:
      enabled: false
      region_id: 999
      region_code: "headscale"
      region_name: "Headscale Embedded DERP"
      stun_listen_addr: "0.0.0.0:3478"
    urls:
      - https://controlplane.tailscale.com/derpmap/default
    paths: []
    auto_update_enabled: true
    update_frequency: 24h
  disable_check_updates: false
  ephemeral_node_inactivity_timeout: 30m
  node_update_check_interval: 10s
  db_type: sqlite3
  db_path: /var/lib/headscale/db.sqlite
  acme_url: https://acme-v02.api.letsencrypt.org/directory
  acme_email: ""
  tls_letsencrypt_hostname: ""
  tls_letsencrypt_cache_dir: /var/lib/headscale/cache
  tls_letsencrypt_challenge_type: HTTP-01
  tls_letsencrypt_listen: ":http"
  tls_cert_path: ""
  tls_key_path: ""
  log:
    format: text
    level: info
  acl_policy_path: ""
  dns_config:
    override_local_dns: true
    nameservers:
      - 1.1.1.1
    domains: []
    magic_dns: true
    base_domain: example.com
  unix_socket: /var/run/headscale/headscale.sock
  unix_socket_permission: "0770"
  logtail:
    enabled: false
  randomize_client_port: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount: {}
